[2024-10-22T11:09:40.350+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-22T11:09:40.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-22T11:09:40.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-22T11:09:40.482+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-10-22T11:09:40.517+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-10-21 00:00:00+00:00
[2024-10-22T11:09:40.531+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp7c4ghpt9']
[2024-10-22T11:09:40.537+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask stream_data_from_api
[2024-10-22T11:09:40.546+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=447) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-22T11:09:40.548+0000] {standard_task_runner.py:64} INFO - Started process 448 to run task
[2024-10-22T11:09:40.767+0000] {task_command.py:426} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-21T00:00:00+00:00 [running]> on host bdd5421c2cdf
[2024-10-22T11:09:41.028+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-21T00:00:00+00:00'
[2024-10-22T11:09:41.030+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-22T11:09:41.894+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=e2e-structured-streaming-kafka-1:9092 <connecting> [IPv4 ('172.21.0.6', 9092)]>: connecting to e2e-structured-streaming-kafka-1:9092 [('172.21.0.6', 9092) IPv4]
[2024-10-22T11:09:41.896+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-10-22T11:09:41.899+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=e2e-structured-streaming-kafka-1:9092 <connecting> [IPv4 ('172.21.0.6', 9092)]>: Connection complete.
[2024-10-22T11:09:42.407+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-10-22T11:09:42.408+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-10-22T11:09:43.379+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:43.387+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:43.389+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:43.391+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:43.494+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:43.496+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:43.497+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:43.499+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:43.602+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:43.604+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:43.607+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:43.608+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:43.714+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:43.716+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:43.717+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:43.719+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:43.873+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:43.874+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:43.875+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:43.876+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:44.029+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:44.030+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:44.032+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:44.038+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:44.293+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:44.296+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:44.297+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:44.298+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:44.562+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:44.564+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:44.572+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:44.575+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:45.031+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:45.033+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:45.037+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:45.039+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:45.499+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:45.503+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:45.505+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:45.506+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:46.366+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:46.368+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:46.369+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:46.371+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:47.240+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:47.243+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:47.245+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:47.246+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:48.328+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:09:48.416+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:48.417+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:48.422+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:48.424+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:49.591+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:49.595+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:49.599+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:49.608+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:50.839+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:50.842+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:50.844+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:50.846+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:52.078+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:52.079+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:52.080+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:52.081+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:53.155+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:53.156+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:53.157+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:53.157+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:53.980+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:09:54.234+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:54.248+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:54.303+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:54.327+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:55.270+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:55.286+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:55.294+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:55.296+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:56.268+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:56.269+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:56.271+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:56.272+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:57.448+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:57.454+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:57.461+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:57.465+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:58.652+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:09:58.663+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:09:58.665+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:58.668+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:09:59.608+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:09:59.850+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:09:59.864+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:09:59.868+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:09:59.873+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:01.050+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:01.052+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:01.055+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:01.058+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:02.236+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:02.242+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:02.245+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:02.248+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:03.426+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:03.430+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:03.433+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:03.437+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:04.469+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:04.479+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:04.484+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:04.488+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:05.517+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:05.523+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:05.528+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:05.534+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:05.844+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:06.428+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:06.432+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:06.436+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:06.451+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:07.347+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:07.349+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:07.350+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:07.351+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:08.375+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:08.378+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:08.381+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:08.383+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:09.409+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:09.414+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:09.417+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:09.420+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:10.348+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:10.355+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:10.406+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:10.415+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:11.245+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:11.250+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:11.253+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:11.262+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:11.980+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:12.176+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:12.181+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:12.185+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:12.190+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:13.128+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:13.143+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:13.150+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:13.159+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:14.086+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:14.091+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:14.095+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:14.099+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:15.072+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:15.078+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:15.082+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:15.090+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:16.321+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:16.322+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:16.323+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:16.324+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:17.541+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:17.545+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:17.554+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:17.557+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:17.719+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:18.534+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:18.536+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:18.538+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:18.538+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:19.547+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:19.549+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:19.550+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:19.551+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:20.761+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:20.762+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:20.764+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:20.766+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:21.980+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:21.982+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:21.984+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:21.986+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:22.894+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:22.896+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:22.898+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:22.899+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:23.229+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:23.809+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:23.811+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:23.812+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:23.813+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:24.928+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:24.930+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:24.931+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:24.941+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:26.058+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:26.059+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:26.060+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:26.061+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:27.149+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:27.151+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:27.153+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:27.154+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:28.225+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:28.231+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:28.245+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:28.249+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:28.657+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:29.435+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:29.441+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:29.444+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:29.446+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:30.579+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:30.582+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:30.588+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:30.591+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:31.563+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:31.564+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:31.565+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:31.566+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:32.545+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:32.549+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:32.554+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:32.555+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:33.531+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:33.565+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:33.582+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:33.594+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:34.236+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:34.576+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:34.606+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:34.613+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:34.616+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:35.816+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:35.823+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:35.827+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:35.831+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:37.014+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:37.032+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:37.065+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:37.069+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:38.245+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:38.249+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:38.253+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:38.257+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:39.441+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:39.445+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:39.449+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:39.456+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:39.839+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:40.638+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:40.644+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:40.648+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:40.656+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:41.881+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:41.886+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:41.890+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:41.896+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:42.774+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:42.777+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:42.780+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:42.782+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:43.702+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:43.706+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:43.714+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:43.718+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:44.950+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:44.956+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:44.961+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:44.965+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:45.423+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:46.208+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:46.216+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:46.221+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:46.233+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:47.459+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:47.464+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:47.467+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:47.471+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:48.701+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:48.706+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:48.716+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:48.721+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:49.906+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:49.906+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:49.909+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:49.910+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:50.998+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:51.101+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:51.102+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:51.103+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:51.105+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:52.226+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:52.234+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:52.240+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:52.250+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:53.384+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:53.388+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:53.396+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:53.401+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:54.473+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:54.476+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:54.478+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:54.480+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:55.550+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:55.552+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:55.555+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:55.557+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:56.459+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:10:56.569+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:56.571+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:56.573+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:56.574+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:57.592+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:57.594+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:57.595+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:57.596+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:58.757+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:10:58.759+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:10:58.762+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:58.763+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:10:59.926+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:10:59.929+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:10:59.930+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:10:59.931+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:01.046+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:01.048+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:01.049+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:01.051+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:01.936+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:11:02.163+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:02.165+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:02.166+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:02.168+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:03.070+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:03.074+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:03.075+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:03.079+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:03.938+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:03.940+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:03.940+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:03.942+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:05.158+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:05.164+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:05.166+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:05.174+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:06.398+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:06.403+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:06.406+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:06.411+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:07.314+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:11:07.638+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:07.643+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:07.647+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:07.650+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:08.903+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:08.907+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:08.909+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:08.914+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:09.936+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:09.938+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:09.940+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:09.941+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:10.965+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:11.026+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:11.081+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:11.100+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:12.150+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:12.160+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:12.163+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:12.168+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:12.894+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:11:13.311+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:13.323+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:13.329+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:13.334+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:14.342+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:14.348+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:14.352+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:14.365+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:15.350+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:15.366+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:15.382+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:15.398+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:16.482+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:16.486+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:16.493+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:16.499+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:17.628+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:17.633+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:17.641+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:17.646+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:18.622+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:11:18.877+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:18.879+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:18.880+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:18.881+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:20.140+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:20.144+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:20.151+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:20.154+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:21.332+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:21.335+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:21.339+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:21.342+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:22.517+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:22.521+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:22.524+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:22.527+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:23.564+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:23.568+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:23.572+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:23.576+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:24.350+0000] {kafka_stream.py:58} ERROR - An error occured: KafkaTimeoutError: Failed to update metadata after 5.0 secs.
[2024-10-22T11:11:24.606+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:24.614+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:24.618+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:24.629+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:25.633+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:25.635+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:25.637+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:25.642+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:26.655+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-10-22T11:11:26.671+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-10-22T11:11:26.686+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:26.692+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:27.915+0000] {conn.py:362} INFO - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-10-22T11:11:27.920+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-10-22T11:11:27.922+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1001 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-22T11:11:27.924+0000] {client_async.py:330} WARNING - Node 1001 connection failed -- refreshing metadata
[2024-10-22T11:11:28.430+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-10-22T11:11:28.438+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-22T11:11:28.460+0000] {process_utils.py:132} INFO - Sending 15 to group 448. PIDs of all processes in the group: [448]
[2024-10-22T11:11:28.466+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 448
[2024-10-22T11:11:28.470+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-22T11:11:28.473+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-22T11:11:28.528+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 54, in stream_data
    producer.send('users_created', json.dumps(res).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 579, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 702, in _wait_on_metadata
    metadata_event.wait(max_wait - elapsed)
  File "/usr/local/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-10-22T11:11:28.636+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=user_automation, task_id=stream_data_from_api, run_id=scheduled__2024-10-21T00:00:00+00:00, execution_date=20241021T000000, start_date=20241022T110940, end_date=20241022T111128
[2024-10-22T11:11:28.725+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=448, status='terminated', exitcode=2, started='11:09:39') (448) terminated with exit code 2
